"""added restaurant

Revision ID: 44c3a555db31
Revises: f3438e82b3d7
Create Date: 2020-06-04 01:41:47.717497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c3a555db31'
down_revision = 'f3438e82b3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('resto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resto_name', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('sun', sa.String(length=20), nullable=True),
    sa.Column('mon', sa.String(length=20), nullable=True),
    sa.Column('tue', sa.String(length=20), nullable=True),
    sa.Column('wed', sa.String(length=20), nullable=True),
    sa.Column('thu', sa.String(length=20), nullable=True),
    sa.Column('fri', sa.String(length=20), nullable=True),
    sa.Column('sat', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('resto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant')
    # ### end Alembic commands ###
