"""added menu

Revision ID: 7ca95bdf3b92
Revises: 44c3a555db31
Create Date: 2020-06-04 12:01:07.122077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca95bdf3b92'
down_revision = '44c3a555db31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('resto_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'resto_description')
    # ### end Alembic commands ###
