"""initial init

Revision ID: a6c32802a593
Revises: 
Create Date: 2020-06-07 01:50:05.820622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c32802a593'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('restaurant',
    sa.Column('resto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resto_name', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('resto_description', sa.String(length=500), nullable=True),
    sa.Column('services', sa.String(length=500), nullable=True),
    sa.Column('sun', sa.String(length=20), nullable=True),
    sa.Column('mon', sa.String(length=20), nullable=True),
    sa.Column('tue', sa.String(length=20), nullable=True),
    sa.Column('wed', sa.String(length=20), nullable=True),
    sa.Column('thu', sa.String(length=20), nullable=True),
    sa.Column('fri', sa.String(length=20), nullable=True),
    sa.Column('sat', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('resto_id'),
    sa.UniqueConstraint('resto_name')
    )
    op.create_table('menu',
    sa.Column('menu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_name', sa.String(length=100), nullable=False),
    sa.Column('menu_description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('resto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resto_id'], ['restaurant.resto_id'], ),
    sa.PrimaryKeyConstraint('menu_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    op.drop_table('restaurant')
    op.drop_table('user')
    op.drop_table('customer')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
