"""added restaurant model

Revision ID: ac5314ae1248
Revises: 016be36c690b
Create Date: 2020-09-02 09:57:56.898555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5314ae1248'
down_revision = '016be36c690b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('restaurant_name', sa.String(length=100), nullable=False),
    sa.Column('restaurant_type', sa.String(length=125), nullable=False),
    sa.Column('business_hours', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('telephone_number', sa.String(length=15), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('restaurant_owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant')
    # ### end Alembic commands ###
