"""established user-restaurant relationship

Revision ID: bb341376df98
Revises: ac5314ae1248
Create Date: 2020-09-02 10:02:50.251365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb341376df98'
down_revision = 'ac5314ae1248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'restaurant', ['restaurant_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='unique')
    # ### end Alembic commands ###
