"""added user and customer names

Revision ID: f3438e82b3d7
Revises: 2058833a0dc6
Create Date: 2020-05-31 01:34:12.097178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3438e82b3d7'
down_revision = '2058833a0dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('customer', 'customer_name')
    # ### end Alembic commands ###
